services:
    php:
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            # if you use supervisor
            #- ./docker/php/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
        build: ./docker/php
        depends_on:
            - postgres
        ports:
#            - 127.0.0.1:${DOCKER_NGINX_PORT}:80
            - 5173:5173

    nginx:
        container_name: ${APP_NAME}_nginx
        image: nginx:1.19
        restart: unless-stopped
        volumes:
            - ./docker/nginx/logs:/var/log/nginx
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - postgres
        ports:
#            - 127.0.0.1:${DOCKER_NGINX_PORT}:80
            - ${DOCKER_NGINX_PORT}:80

    postgres:
        image: postgres:12
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/postgres/db:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:${DB_PORT}:5432



#    redis:
#        image: redis:6.0.10-alpine
#        restart: unless-stopped
#        container_name: ${APP_NAME}_redis
